# MIT License
#
# Copyright (c) [2024] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -------------------------------------- IMPORTS -----------------------------------------------------------------------

import asyncio
import functools
import inspect
import logging
import socket
import time
from pathlib import Path
from typing import Annotated, Any, Callable, Dict, List, Literal, Optional

import apps.web.save_viewer_state as SaveViewerState
import uvicorn
from fastmcp import FastMCP
from pydantic import Field
from mcp.types import Icon, ToolAnnotations
from starlette.requests import Request
from starlette.responses import JSONResponse

from lib.error_status import PngError, PngHttpPortInUseError
from lib.event_counter import EventCounter
from lib.ipc import IpcDealerAsync
from lib.web_server import get_socket_for_uvicorn
from meta.meta import APP_NAME

from .tools.get_car_damage import CAR_DAMAGE_OUTPUT_SCHEMA, get_car_damage
from .tools.get_driver_lap_times import (DRIVER_LAP_TIMES_OUTPUT_SCHEMA,
                                         get_driver_lap_times)
from .tools.get_drivers_list import (DRIVERS_LIST_OUTPUT_SCHEMA,
                                     get_drivers_list)
from .tools.get_f1_25_setup_guide import (
    F1_SETUP_GUIDE_OUTPUT_SCHEMA, get_f1_setup_guide)
from .tools.get_fuel_info import FUEL_INFO_OUTPUT_SCHEMA, get_fuel_info
from .tools.get_player_driver_info import (PLAYER_DRIVER_INFO_OUTPUT_SCHEMA,
                                           get_player_driver_info)
from .tools.get_player_fuel_info import (PLAYER_FUEL_INFO_OUTPUT_SCHEMA,
                                         get_player_fuel_info)
from .tools.get_player_tyre_wear import (PLAYER_TYRE_WEAR_OUTPUT_SCHEMA,
                                         get_player_tyre_wear)
from .tools.get_race_table import RACE_TABLE_OUTPUT_SCHEMA, get_race_table
from .tools.get_session_events_for_driver import (
    DRIVER_SESSION_EVENTS_OUTPUT_SCHEMA, get_session_events_for_driver)
from .tools.get_session_info import (SESSION_INFO_OUTPUT_SCHEMA,
                                     get_session_info)
from .tools.get_saved_sessions import (
    SAVED_SESSION_OUTPUT_SCHEMA, SAVED_SESSIONS_LIST_OUTPUT_SCHEMA,
    get_saved_session_driver_info, get_saved_session_summary,
    list_saved_sessions)
from .tools.get_tyre_wear import TYRE_WEAR_OUTPUT_SCHEMA, get_tyre_wear
from .tools.race_analysis import (
    COACH_NOTES_OUTPUT_SCHEMA, DATA_QUALITY_REPORT_OUTPUT_SCHEMA,
    EVENT_TIMELINE_OUTPUT_SCHEMA, PACE_ANALYSIS_OUTPUT_SCHEMA,
    PIT_STOPS_OUTPUT_SCHEMA, PLAYER_RACE_SUMMARY_OUTPUT_SCHEMA,
    RIVAL_COMPARISON_OUTPUT_SCHEMA, STRATEGY_SUMMARY_OUTPUT_SCHEMA,
    compare_driver_to_rivals, get_coach_notes, get_data_quality_report,
    get_driver_event_timeline, get_driver_pace_analysis,
    get_pit_stops, get_player_race_summary, get_strategy_summary)

MAX_CAR_INDEX = 24
DriverIndex = Annotated[int, Field(ge=0, le=MAX_CAR_INDEX)]
TransportType = Literal["http", "stdio"]

# -------------------------------------- FUNCTIONS ---------------------------------------------------------------------

class MCPBridge:
    """FastMCP-based MCP Bridge for sim racing telemetry"""

    WELCOME_MSG = """\
This MCP server provides authoritative, local, live telemetry and session state
for a sim racing session generated by the Pits n' Giggles application.

Rules:
- Live session data is ONLY available through MCP tools.
- Do NOT use web search for session-specific information.
- Treat MCP tool responses as the single source of truth.
- If a tool reports available=false, the data is currently unavailable.
- If a tool reports connected=false, the data source is disconnected. The data may be outdated.
    - Check for the last-update-timestamp field if available and use it to determine data freshness.
- Do not speculate or infer missing information.

Tools exposed by this MCP provide structured snapshots of the current session.
They are safe to call whenever up-to-date information is required.

TIME AND UNIT HANDLING (MANDATORY):

All time values returned by MCP tools are in milliseconds unless explicitly stated otherwise.

You MUST convert all time values before presenting them to the user using the following formats:

- Lap times MUST be formatted as: mm:ss.sss
- Sector times MUST be formatted as: ss.sss
- Time deltas MUST be formatted as: +s.sss or -s.sss

Rules:
- NEVER display raw milliseconds to the user.
- NEVER mix formats.
- If a value cannot be converted due to missing context, state that it is unavailable.

TYRE WEAR THRESHOLDS:

- Tyre wear above 80% on any individual tyre risks a puncture.
- Proactively warn the user when any tyre wear value exceeds this threshold.

"""

    def __init__(
        self,
        dealer: IpcDealerAsync,
        logger: logging.Logger,
        version: str,
        session_dir: Path,
        *,
        transport: TransportType = "stdio",
        host: str = "127.0.0.1",
        port: int = 8000,
    ) -> None:
        self.logger = logger
        self.version = version
        self.transport = transport
        self.host = host
        self.port = port
        self.dealer = dealer
        self.session_dir = session_dir

        self.stats = EventCounter()
        SaveViewerState.init_state(logger)

        # FastMCP server
        self.mcp = FastMCP(
            name=f"{APP_NAME} MCP Server",
            instructions=self.WELCOME_MSG,
            strict_input_validation=True,
            version=self.version,
            website_url="https://www.pitsngiggles.com/",
            icons=[
                 Icon(
                      src="https://raw.githubusercontent.com/ashwin-nat/pits-n-giggles/refs/heads/main/assets/logo.png",
                      mimeType="image/png",
                 )
            ]
        )

        self._register_tools()
        self.logger.debug("MCPBridge initialized (transport=%s)", transport)

    # ------------------------------------------------------------------
    # Tool registration
    # ------------------------------------------------------------------

    def _tool(self, name: str, **kwargs) -> Callable:
        """Decorator factory: registers an MCP tool and wraps it to record
        per-tool call counts and processing-time latency via EventCounter."""
        def decorator(fn: Callable) -> Callable:
            @functools.wraps(fn)
            async def _instrumented(*args, **kw):
                start_ns = time.time_ns()
                try:
                    return await fn(*args, **kw)
                finally:
                    self.stats.track_event("__MCP_TOOLS__", name)
                    self.stats.track_packet_latency("__MCP_LATENCY__", name, start_ns)
            _instrumented.__signature__ = inspect.signature(fn)
            self.mcp.tool(name=name, **kwargs)(_instrumented)
            return _instrumented
        return decorator

    def _register_tools(self) -> None:

        @self._tool(
            name="get_session_info",
            description=(
                "Get global session metadata: circuit name, session type (Race/Qualifying/Practice), "
                "formula type, lap progress, time remaining, air/track temperatures, weather forecast, "
                "safety car status and deployment counts, red flag count, and spectating flag. "
                "Use this to orient yourself before calling per-driver tools."
            ),
            title="Session Information - Globals",
            tags={"session", "weather", "safetyCar"},
            output_schema=SESSION_INFO_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Session Information",
                readOnlyHint=True,
                openWorldHint=False,
            )
        )
        async def get_session_info_tool():
            rsp = get_session_info(self.logger)
            self.logger.debug("get_session_info called: available=%s", rsp.get("available", False))
            return rsp

        @self._tool(
            name="get_f1_setup_guide",
            description=(
                "Get the bundled F1 setup guide derived from f1_25_setups.xlsx or f1_26_setups.xlsx. "
                "Pass a circuit name to retrieve recommended aero, differential, suspension, brakes, "
                "tyre pressures, compounds, 50% strategy, lap count, and notes for that circuit. "
                "Pass game_year=2025 or game_year=2026. If game_year or circuit is omitted, "
                "the current live session is used when available. "
                "Unavailable F1 26 fields are returned as null and listed in unavailable_fields. "
                "Set include_all=true to return every setup for the selected guide."
            ),
            title="F1 Setup Guide",
            tags={"setup", "f1-25", "f1-26", "strategy", "circuit"},
            output_schema=F1_SETUP_GUIDE_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="F1 Setup Guide",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def get_f1_setup_guide_tool(
            circuit: Annotated[Optional[str], Field(description="Optional circuit name. If omitted, the current live session circuit is used when available.")] = None,
            game_year: Annotated[Optional[int], Field(ge=2025, le=2026, description="Setup guide year. Use 2025 for F1 25 or 2026 for F1 26. If omitted, the current live session game year is used when available.")] = None,
            include_all: Annotated[bool, Field(description="Return all setups for the selected game year in addition to the matched circuit setup.")] = False,
        ) -> Dict[str, Any]:
            rsp = get_f1_setup_guide(
                logger=self.logger,
                circuit=circuit,
                game_year=game_year,
                include_all=include_all,
            )
            self.logger.debug(
                "get_f1_setup_guide called: circuit=%s game_year=%s include_all=%s ok=%s",
                circuit,
                game_year,
                include_all,
                rsp.get("ok", False),
            )
            return rsp

        @self._tool(
            name="get_race_table",
            description=(
                "Get a full snapshot of the current race standings for every driver on the grid. "
                "Each entry includes: position, driver name, team, DNF status, delta to leader (ms), "
                "last/best lap times (ms), speed trap, tyre compound/age/wear per corner, "
                "tyre wear rate (% per lap), fuel rate, fuel surplus laps (live and game estimates), "
                "ERS percentage/mode, and front wing damage. "
                "Use this for standings comparisons, strategy analysis, or any multi-driver overview. "
                "For per-driver detail (full lap history, race control events, car damage), "
                "call the dedicated per-driver tools instead."
            ),
            title="Current Race State",
            tags={
                "race",
                "standings",
                "compare",
                "snapshot",
            },
            output_schema=RACE_TABLE_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Current Race State",
                readOnlyHint=True,
                openWorldHint=False,
            )
        )
        async def get_race_table_tool():
            rsp = get_race_table(self.logger)
            self.logger.debug("get_race_table called: available=%s", rsp.get("available", False))
            return rsp

        @self._tool(
            name="get_drivers_list",
            description=(
                "Get the list of all drivers in the current session with their index, name, team, "
                "driver number, grid position, and telemetry-sharing setting. "
                "Call this first to resolve a driver name to an index before calling any tool "
                "that requires a driver_index parameter."
            ),
            title="Drivers List",
            tags={
                "drivers",
                "session",
                "participants",
            },
            output_schema=DRIVERS_LIST_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Drivers List",
                readOnlyHint=True,
                openWorldHint=False,
            )
        )
        async def get_drivers_list_tool():
            rsp = get_drivers_list(self.logger)
            self.logger.debug("get_drivers_list called: available=%s", rsp.get("available", False))
            return rsp

        @self._tool(
            name="get_driver_lap_times",
            description=(
                "Get the complete lap-by-lap time history for a driver identified by index. "
                "Returns each lap's overall time, three sector times (all in ms), top speed, "
                "and validity flags for the lap and each sector. "
                "Also returns the lap numbers that set the driver's personal-best lap time and "
                "each sector best. Use get_drivers_list to look up a driver's index."
            ),
            title="Driver Lap Times (History)",
            tags={
                "driver",
                "laps",
                "timing",
                "history",
                "consistency",
                "pace",
            },
            output_schema=DRIVER_LAP_TIMES_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Lap Times (History)",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_driver_lap_times(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_driver_lap_times called: driver_index=%s", driver_index)
            return await get_driver_lap_times(
                dealer=self.dealer,
                logger=self.logger,
                driver_index=driver_index,
            )

        @self._tool(
            name="get_session_events_for_driver",
            description=(
                "Get all race control messages logged for a specific driver during the current session. "
                "Covers fastest laps, penalties (type and infringement), overtakes, collisions, "
                "pit stops, tyre changes, wing changes, car damage events, retirements, safety car, "
                "DRS enable/disable, red flags, and more. "
                "Each message includes lap number, timestamp, and a plain-English description. "
                "Use get_drivers_list to look up a driver's index."
            ),
            title="Driver Race Control Messages (History)",
            tags={
                "driver",
                "events",
                "key",
                "notable",
                "raceControl",
                "incidents",
            },
            output_schema=DRIVER_SESSION_EVENTS_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Race Control Messages (History)",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_session_events_for_driver(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_session_events_for_driver called: driver_index=%s", driver_index)
            return await get_session_events_for_driver(
                dealer=self.dealer,
                logger=self.logger,
                driver_index=driver_index,
            )

        @self._tool(
            name="get_player_driver_info",
            description=(
                "Get the identity of the player or currently-spectated driver: "
                "their index, name, team, telemetry setting, and flags indicating "
                "whether they are the actual player or a spectated AI. "
                "Use this to resolve 'my driver' before calling per-driver tools, "
                "without needing to scan get_drivers_list manually."
            ),
            title="Player/Reference Driver Info",
            tags={
                "player",
                "reference",
                "ref",
                "pov",
                "driver",
                "info",
            },
            output_schema=PLAYER_DRIVER_INFO_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Player/Reference Driver Info",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_player_driver_info():
            return get_player_driver_info(self.logger)

        @self._tool(
            name="get_player_fuel_info",
            description=(
                "Get fuel telemetry for the player or currently-spectated driver: "
                "fuel remaining (kg), tank capacity, fuel mix setting, last-lap consumption, "
                "rolling average burn rate, target burn rate and next-lap target (race sessions only), "
                "and surplus/deficit expressed as laps — both from the live model and the game's built-in estimate. "
                "data_sufficient is false until at least 2 racing laps are complete; "
                "live estimates and targets are null until then."
            ),
            title="Player Fuel Info",
            tags={"player", "fuel", "consumption", "strategy"},
            output_schema=PLAYER_FUEL_INFO_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Player Fuel Info",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_player_fuel_info() -> Dict[str, Any]:
            self.logger.debug("get_player_fuel_info called")
            return get_player_fuel_info(logger=self.logger)

        @self._tool(
            name="get_fuel_info",
            description=(
                "Get fuel telemetry for a specific driver by index: "
                "fuel remaining (kg), tank capacity, fuel mix setting, last-lap consumption, "
                "rolling average burn rate, target burn rate and next-lap target (race sessions only), "
                "and surplus/deficit expressed as laps — both from the live model and the game's built-in estimate. "
                "data_sufficient is false until at least 2 racing laps are complete; "
                "live estimates and targets are null until then. "
                "Use get_drivers_list to look up a driver's index."
            ),
            title="Driver Fuel Info",
            tags={"driver", "fuel", "consumption", "strategy"},
            output_schema=FUEL_INFO_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Fuel Info",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_fuel_info(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_fuel_info called: driver_index=%s", driver_index)
            return get_fuel_info(logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="get_player_tyre_wear",
            description=(
                "Get tyre telemetry for the player or currently-spectated driver: "
                "compound, tyre age (laps), per-corner wear percentage (FL/FR/RL/RR), "
                "average wear across all four tyres, and per-corner wear rate (% per lap) "
                "derived from linear regression. wear_rate_available is false until at "
                "least 2 laps of data exist; rates are null until then. "
                "Warn the user if any individual tyre wear exceeds 80%."
            ),
            title="Player Tyre Wear",
            tags={"player", "tyre", "wear", "strategy"},
            output_schema=PLAYER_TYRE_WEAR_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Player Tyre Wear",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_player_tyre_wear() -> Dict[str, Any]:
            self.logger.debug("get_player_tyre_wear called")
            return get_player_tyre_wear(logger=self.logger)

        @self._tool(
            name="get_tyre_wear",
            description=(
                "Get tyre telemetry for a specific driver by index: "
                "compound, tyre age (laps), per-corner wear percentage (FL/FR/RL/RR), "
                "average wear across all four tyres, and per-corner wear rate (% per lap) "
                "derived from linear regression. wear_rate_available is false until at "
                "least 2 laps of data exist; rates are null until then. "
                "Warn the user if any individual tyre wear exceeds 80%. "
                "Use get_drivers_list to look up a driver's index."
            ),
            title="Driver Tyre Wear",
            tags={"driver", "tyre", "wear", "strategy"},
            output_schema=TYRE_WEAR_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Tyre Wear",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_tyre_wear(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_tyre_wear called: driver_index=%s", driver_index)
            return get_tyre_wear(logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="get_car_damage",
            description=(
                "Get detailed car damage state for a driver by index: "
                "per-corner tyre wear and tyre damage, brake damage, "
                "front/rear wing damage, floor, diffuser, and sidepod damage, "
                "DRS and ERS fault flags, gearbox damage, "
                "and individual engine component wear (ICE, MGU-H, MGU-K, ES, CE, TC). "
                "Also reports whether the engine is blown or seized. "
                "Use get_drivers_list to look up a driver's index."
            ),
            title="Car Damage Info",
            tags={
                "driver",
                "car",
                "damage",
                "info",
            },
            output_schema=CAR_DAMAGE_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Car Damage Info",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_car_damage(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_car_damage called: driver_index=%s", driver_index)
            return await get_car_damage(
                dealer=self.dealer,
                logger=self.logger,
                driver_index=driver_index,
            )

        @self._tool(
            name="get_player_race_summary",
            description=(
                "Get a consolidated race-review summary for the player or currently-spectated driver. "
                "Includes final/start position, positions gained or lost, best lap, clean race pace "
                "excluding pit laps, pit stops, penalties, damage, fuel remaining, tyre wear summary, "
                "and key events. Use this first for post-race reviews instead of stitching several tools together."
            ),
            title="Player Race Summary",
            tags={"player", "race", "summary", "review", "pace", "strategy"},
            output_schema=PLAYER_RACE_SUMMARY_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Player Race Summary",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_player_race_summary() -> Dict[str, Any]:
            self.logger.debug("get_player_race_summary called")
            return await get_player_race_summary(dealer=self.dealer, logger=self.logger)

        @self._tool(
            name="get_pit_stops",
            description=(
                "Detect pit stops for a driver using pit-lane/tyre-change events, abnormal lap-time spikes, "
                "tyre compound or age resets, top-speed drops, and position loss. "
                "Use this when a lap looks slow and you need to distinguish a pit stop from a mistake or incident."
            ),
            title="Driver Pit Stop Detector",
            tags={"driver", "pit", "strategy", "stints"},
            output_schema=PIT_STOPS_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Pit Stop Detector",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_pit_stops(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_pit_stops called: driver_index=%s", driver_index)
            return await get_pit_stops(dealer=self.dealer, logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="get_driver_pace_analysis",
            description=(
                "Analyze a driver's clean pace. Returns fastest lap, median lap, average lap, "
                "average excluding pit laps, lap-time consistency/std dev, stint pace, personal-best sector laps, "
                "and invalid laps removed."
            ),
            title="Driver Clean Pace Analysis",
            tags={"driver", "pace", "laps", "consistency", "stints"},
            output_schema=PACE_ANALYSIS_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Clean Pace Analysis",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_driver_pace_analysis(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_driver_pace_analysis called: driver_index=%s", driver_index)
            return await get_driver_pace_analysis(dealer=self.dealer, logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="get_driver_event_timeline",
            description=(
                "Classify raw race-control messages for a driver into readable event phases: overtakes made/lost, "
                "pit stops, penalties, fastest laps, damage, safety car, DRS enabled, and tyre changes."
            ),
            title="Driver Event Timeline",
            tags={"driver", "events", "timeline", "raceControl"},
            output_schema=EVENT_TIMELINE_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Event Timeline",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_driver_event_timeline(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_driver_event_timeline called: driver_index=%s", driver_index)
            return await get_driver_event_timeline(dealer=self.dealer, logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="get_strategy_summary",
            description=(
                "Summarize a driver's strategy and stints. Returns stint compounds, lap ranges, average pace, pit laps, "
                "undercut/overcut position effect, tyre wear per stint, and compound comparison."
            ),
            title="Driver Strategy Summary",
            tags={"driver", "strategy", "stints", "tyres", "pit"},
            output_schema=STRATEGY_SUMMARY_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Strategy Summary",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_strategy_summary(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_strategy_summary called: driver_index=%s", driver_index)
            return await get_strategy_summary(dealer=self.dealer, logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="compare_driver_to_rivals",
            description=(
                "Compare one driver with nearby rivals or an explicit rival list. Returns best-lap gap, average clean "
                "pace gap, sector comparison, top-speed comparison, tyre wear comparison, and ERS/fuel at finish."
            ),
            title="Driver Rival Comparison",
            tags={"driver", "compare", "rivals", "pace", "sectors"},
            output_schema=RIVAL_COMPARISON_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Rival Comparison",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_compare_driver_to_rivals(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
            rival_indices: Annotated[Optional[List[DriverIndex]], Field(description="Optional list of rival driver indices. If omitted, nearby rivals by position are used.")] = None,
        ) -> Dict[str, Any]:
            self.logger.debug(
                "compare_driver_to_rivals called: driver_index=%s rival_indices=%s",
                driver_index,
                rival_indices,
            )
            return await compare_driver_to_rivals(
                dealer=self.dealer,
                logger=self.logger,
                driver_index=driver_index,
                rival_indices=rival_indices,
            )

        @self._tool(
            name="get_data_quality_report",
            description=(
                "Report telemetry confidence/anomaly flags such as missing top-speed data, null delta-to-leader, "
                "and session-state inconsistencies. Use this before making strong claims from incomplete data."
            ),
            title="Data Quality Report",
            tags={"quality", "confidence", "anomaly", "data"},
            output_schema=DATA_QUALITY_REPORT_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Data Quality Report",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_data_quality_report() -> Dict[str, Any]:
            self.logger.debug("get_data_quality_report called")
            return await get_data_quality_report(dealer=self.dealer, logger=self.logger)

        @self._tool(
            name="get_coach_notes",
            description=(
                "Generate natural-language-ready structured coaching notes for a driver. "
                "Returns what went well, what cost time, where to improve, one-lap pace, race management, "
                "and next race focus."
            ),
            title="Driver Coach Notes",
            tags={"driver", "coach", "notes", "review", "pace"},
            output_schema=COACH_NOTES_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Coach Notes",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_coach_notes(
            driver_index: Annotated[DriverIndex, Field(description="Driver index. Use get_drivers_list to resolve a name to an index.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_coach_notes called: driver_index=%s", driver_index)
            return await get_coach_notes(dealer=self.dealer, logger=self.logger, driver_index=driver_index)

        @self._tool(
            name="list_saved_sessions",
            description=(
                "List saved historical sessions from disk, newest first. "
                "Returns stable session slugs plus metadata such as track, session type, date, "
                "formula, lap counts, and best lap/sector/pace fields where available. "
                "Use this first when the user asks about a previous, saved, historical, or past session."
            ),
            title="Saved Sessions List",
            tags={"saved", "history", "sessions", "previous"},
            output_schema=SAVED_SESSIONS_LIST_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Saved Sessions List",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_list_saved_sessions(
            limit: Annotated[int, Field(ge=1, le=100, description="Maximum number of saved sessions to return.")] = 20,
            offset: Annotated[int, Field(ge=0, description="Number of saved sessions to skip from the newest-first list.")] = 0,
        ) -> Dict[str, Any]:
            self.logger.debug("list_saved_sessions called: limit=%s offset=%s", limit, offset)
            return await list_saved_sessions(
                session_dir=self.session_dir,
                logger=self.logger,
                app_version=self.version,
                limit=limit,
                offset=offset,
            )

        @self._tool(
            name="get_saved_session_summary",
            description=(
                "Get session-level data for a saved historical session by slug. "
                "Includes the saved telemetry table, session metadata, fastest records, "
                "overtake records, position history, tyre stint history, speed trap records, "
                "custom markers, and race-control data if it was saved."
            ),
            title="Saved Session Summary",
            tags={"saved", "history", "summary", "race"},
            output_schema=SAVED_SESSION_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Saved Session Summary",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_saved_session_summary(
            slug: Annotated[str, Field(min_length=1, description="Saved session slug returned by list_saved_sessions.")],
        ) -> Dict[str, Any]:
            self.logger.debug("get_saved_session_summary called: slug=%s", slug)
            return await get_saved_session_summary(
                session_dir=self.session_dir,
                logger=self.logger,
                app_version=self.version,
                slug=slug,
            )

        @self._tool(
            name="get_saved_session_driver_info",
            description=(
                "Get detailed per-driver data from a saved historical session by slug and driver index. "
                "Includes lap history, final classification, tyre set history, per-lap snapshots, "
                "car status, car damage, penalties, collisions, setup/participant data, and race-control "
                "messages if they were saved."
            ),
            title="Saved Session Driver Detail",
            tags={"saved", "history", "driver", "laps"},
            output_schema=SAVED_SESSION_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Saved Session Driver Detail",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_saved_session_driver_info(
            slug: Annotated[str, Field(min_length=1, description="Saved session slug returned by list_saved_sessions.")],
            driver_index: Annotated[DriverIndex, Field(description="Driver index within the saved session.")],
        ) -> Dict[str, Any]:
            self.logger.debug(
                "get_saved_session_driver_info called: slug=%s driver_index=%s",
                slug,
                driver_index,
            )
            return await get_saved_session_driver_info(
                session_dir=self.session_dir,
                logger=self.logger,
                app_version=self.version,
                slug=slug,
                driver_index=driver_index,
            )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def run(self) -> None:
        """
        Long-running MCP server coroutine.
        Intended to be scheduled with asyncio.create_task().
        """

        logging.getLogger("uvicorn.error").setLevel(logging.CRITICAL)
        logging.getLogger("uvicorn.lifespan").setLevel(logging.CRITICAL)
        logging.getLogger("starlette").setLevel(logging.CRITICAL)

        try:
            if self.transport == "http":
                # 1. Bind the socket ourselves — this is where port-conflict
                #    errors surface cleanly, before uvicorn is involved at all.
                sock = self._bind_socket()
                self.logger.debug("Starting MCP server (transport=%s port=%s)", self.transport, self.port)

                # 2. Get the ASGI app out of FastMCP without starting a server.
                asgi_app = self.mcp.http_app()
                asgi_app.add_route("/test", self._test_endpoint, methods=["GET"])

                # 3. Configure uvicorn but tell it NOT to bind — we already did.
                config = uvicorn.Config(
                    app=asgi_app,
                    host=self.host,
                    port=self.port,
                    log_level="critical",   # we use our own logger
                    access_log=False,
                )

                # Since we're running uvicorn ourselves, we need to lay hands on FastMCP's internals for cleanup
                server = uvicorn.Server(config)
                async with self.mcp._lifespan_manager():
                    await server.serve(sockets=[sock])

            elif self.transport == "stdio":
                self.logger.debug(
                    "Starting MCP server (transport=%s)", self.transport
                )
                await self.mcp.run_async(
                    transport="stdio",
                    show_banner=False,
                )
            else:
                raise ValueError(f"Unsupported transport: {self.transport}")

        except asyncio.CancelledError:
            return # silent handling - this is expected

        # Handled in main
        except PngError:
            raise

        except Exception as e:
            self.logger.exception("MCP server failed: %s", e)
            raise

    def get_stats(self) -> Dict[str, Any]:
        """Get stats for the MCP server."""
        return self.stats.get_stats()

    def _bind_socket(self) -> socket.socket:
        """Create and bind a TCP socket, raising on port conflict.

        Platform-specific options:
        - Windows: SO_EXCLUSIVEADDRUSE makes bind() fail immediately when the
          port is already in use.  Without it Windows silently allows the bind.
        - Unix/Linux/macOS: SO_REUSEADDR lets us bind to a port that is in
          TIME_WAIT (safe for quick restart) but still fails when another
          process is actively listening.
        """
        try:
            sock = get_socket_for_uvicorn(self.port, host=self.host)
            return sock
        except PngHttpPortInUseError as e:
            self.logger.exception("Port %d is already in use", self.port)
            raise e
        except OSError as e:
            self.logger.exception("Failed to start server: %s", e)
            raise

    async def _test_endpoint(self, _request: Request) -> str:
        """Simple test endpoint that returns text."""
        return JSONResponse({
            "message": f"Pits n' Giggles MCP Server v{self.version}",
        })
